"""empty message

Revision ID: 066254dff96e
Revises: c25c4b14e487
Create Date: 2025-01-30 17:13:42.572879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066254dff96e'
down_revision = 'c25c4b14e487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ingredient',
    sa.Column('foodie_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foodie_id'], ['foodie.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('foodie_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ingredient')
    # ### end Alembic commands ###
