"""empty message

Revision ID: 22da7abd9da5
Revises: c8f838debcca
Create Date: 2025-02-10 04:07:19.385020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22da7abd9da5'
down_revision = 'c8f838debcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###
