"""empty message

Revision ID: 358f74863b1d
Revises: f78ea4681e82
Create Date: 2025-01-29 01:33:20.204577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358f74863b1d'
down_revision = 'f78ea4681e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###