"""empty message

Revision ID: 371eb7abf3b7
Revises: 77de4e69a90b
Create Date: 2025-01-24 23:57:45.107184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371eb7abf3b7'
down_revision = '77de4e69a90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
