"""empty message

Revision ID: 614076604944
Revises: 
Create Date: 2025-01-24 15:22:41.353027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614076604944'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('foodie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foodie_id'], ['foodie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('foodie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foodie_id'], ['foodie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ingredient',
    sa.Column('foodie_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foodie_id'], ['foodie.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('foodie_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ingredient')
    op.drop_table('shopping_note')
    op.drop_table('recipe')
    op.drop_table('ingredient')
    op.drop_table('foodie')
    # ### end Alembic commands ###
