"""empty message

Revision ID: 881f285c7883
Revises: 371eb7abf3b7
Create Date: 2025-01-27 22:10:23.031464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881f285c7883'
down_revision = '371eb7abf3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodie', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###