"""empty message

Revision ID: f78ea4681e82
Revises: 881f285c7883
Create Date: 2025-01-29 01:27:40.526702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78ea4681e82'
down_revision = '881f285c7883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ingredient')
    with op.batch_alter_table('foodie', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('user_ingredient',
    sa.Column('foodie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['foodie_id'], ['foodie.id'], name='user_ingredient_foodie_id_fkey'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='user_ingredient_ingredient_id_fkey'),
    sa.PrimaryKeyConstraint('foodie_id', 'ingredient_id', name='user_ingredient_pkey')
    )
    # ### end Alembic commands ###